# echidna_config.yaml

#### Primary testing options
testMode:       "property"    # use user-defined boolean properties
testLimit:      50000         # total number of generated tests
seqLen:         100           # maximum transaction sequence length
shrinkLimit:    5000          # how many shrink attempts on counterexamples

#### I/O and output format
format:         "text"        # one of: "text", "json", "none"
corpusDir:      "corpus"      # directory of seed transactions
timeout:        120           # seconds to run before automatic exit
workers:        1             # parallel worker threads

#### Coverage
coverage:       true          # collect/emit coverage reports

#### Sender accounts (as hex strings)
sender:
  - "0x0000000000000000000000000000000000001000"
  - "0x0000000000000000000000000000000000002000"
  - "0x0000000000000000000000000000000000003000"

#### Contract deployment parameters
deployer:       "0x0000000000000000000000000000000000000000"
contractAddr:   "0x0a329c0648769A73afAc7F9381E08FB43dBEA72"

#### Advanced options
multi-abi:      false         # allow multiple ABIs in single file?
cryticArgs:     []            # arguments passed to crytic (must be a list)
solcArgs:       ""            # arguments passed to solc (must be a single string)
solcLibs:       []            # library remapping, e.g. ["Lib1:./lib1.sol"]
quiet:          false         # supress extraneous output

#### Multi-Layer Fuzzing Optimization Framework
preDilutionFunctions:
  - "transfer"
  - "approve"
  - "withdraw"
  - "deposit"
  - "burn"
  - "mint"
  - "swap"
preDilutionWeight: 0.35         # Each priority function gets 35% weight

#### Smart Array Mutation Parameters
smartMutation: true            # Enable enhanced mutation strategies
mutationDepth: 3              # Layers of mutation (1-5)
priorityMutationRate: 0.8     # Higher mutation rate for priority functions
normalMutationRate: 0.3       # Lower rate for normal functions

#### Differential Treatment Strategies
differentialTreatment: true    # Enable different strategies per function type
prioritySequenceLength: 150   # Longer sequences for priority functions
normalSequenceLength: 50      # Shorter sequences for normal functions
priorityGasLimit: 8000000     # Higher gas limit for priority functions
normalGasLimit: 3000000       # Standard gas limit for normal functions

#### Advanced Optimization Features
adaptiveFuzzing: true         # Enable adaptive strategy selection
crossoverRate: 0.6           # Genetic algorithm crossover rate
elitismRate: 0.1             # Keep best 10% of test cases
diversityThreshold: 0.7      # Maintain test case diversity

#### Multi-Objective Optimization
optimizationTargets:
  - "coverage"               # Maximize code coverage
  - "bug_detection"          # Prioritize bug finding
  - "edge_case_discovery"    # Find unusual execution paths
  - "state_space_exploration" # Explore contract states

#### Layered Strategy Configuration
strategyLayers:
  - ["layer1", "predilution"]      # Priority function selection
  - ["layer2", "smart_mutation"]   # Enhanced mutations
  - ["layer3", "differential"]     # Different treatment strategies
  - ["layer4", "adaptive"]         # Dynamic strategy adjustment

# Enhanced fuzzing parameters
seed: 42                     # Reproducible random seed
dictFreq: 0.6               # Higher dictionary usage
maxArraySize: 1000          # Larger arrays for complex testing
